### ISSUE TITLE
[BUG] Unable to make it work

### ISSUE THREAD

**Issue by jhmk** [pilosus/dienstplan#118]
Hi, need some help with the setup.

When using the @dienstplan command in slack nothing happens. 
Also on the Server I don't see any incoming Network Traffic or anything in the access & error.log from nginx.

How the setup looks like:
1. created a ubuntu server on AWS including a domain + nginx + certbot to have HTTPS
2. allowed traffic via Port 80,443 and 8080
3. created docker container by cloning the Repo and run:
```
make build
make up
make migrate
```
4. created the Slack App with the YAML Manifest
```
_metadata:
  major_version: 1
  minor_version: 1
display_information:
  name: dienstplan
  description: Slack bot for duty rotations
  background_color: "#002087"
features:
  bot_user:
    display_name: dienstplan
    always_online: false
oauth_config:
  scopes:
    bot:
      - app_mentions:read
      - channels:read
      - chat:write
      - chat:write.customize
settings:
  event_subscriptions:
    request_url: https://slack-dienstplan.MYDOMAIN/api/events
    bot_events:
      - app_mention
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: false
```

Docker container are running:
```
CONTAINER ID   IMAGE                      COMMAND                  CREATED       STATUS       PORTS                                                                                    NAMES
7cc441353a6e   dienstplan-dienstplan      "entrypoint clojure …"   2 hours ago   Up 2 hours   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 0.0.0.0:16543->6543/tcp, :::16543->6543/tcp   dienstplan-dienstplan-1
756c85897107   postgres:16.2-alpine3.19   "docker-entrypoint.s…"   2 hours ago   Up 2 hours   0.0.0.0:15432->5432/tcp, :::15432->5432/tcp                                              dienstplan-postgres-1
```

Because I'm using NGINX do I need to make a Proxy Upstream to the docker container on Port 8080?
When running curl to test the Server I get this error:
```
curl https://slack-dienstplan.DOMAIN:8080/api/events
curl: (35) LibreSSL/3.3.6: error:1404B42E:SSL routines:ST_CONNECT:tlsv1 alert protocol version
```

No error on: 
`curl https://slack-dienstplan.DOMAIN   `
